### ISSUE TITLE
Figure Out How to Run Multiple Services In Docker

### ISSUE THREAD

**Issue by Nate-Louder** [NACAGA/Message-Board-Micro-Service#22]
We need a simple way to spin up multiple services and their respective databases. Not sure exactly how that works.

**Comment by ckinateder** [comment]
May want to add delays between startup if the required container needs a few more seconds to safely start working.
```
version: "3.7"

services:
  web:
    image: nginx:latest
    entrypoint: ["sleep", "5"]
```
